import path from "node:path";

import { unified } from "@astrojs/markdown-remark";
import react from "@astrojs/react";
import starlight from "@astrojs/starlight";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, passthroughImageService } from "astro/config";
import starlightLinksValidator from "starlight-links-validator";

import { rehypeCardImages } from "./src/plugins/rehypeCardImages.js";

const base = "/frontend";

// `pnpm dev:backend` serves the card endpoints; override to point at another instance.
const BACKEND_ORIGIN = process.env.BACKEND_ORIGIN ?? "http://localhost:9000";

/*
 * One app: Starlight serves the docs under `/frontend/docs`, and the card
 * wizard is a page of the same site at `/frontend`.
 */
export default defineConfig({
  site: "https://github-stats-extended.vercel.app",
  base,
  outDir: "./build",
  // One screenshot; not worth a native image dependency.
  image: { service: passthroughImageService() },
  markdown: {
    // Starlight appends its own plugins to whatever processor is configured here.
    processor: unified({
      rehypePlugins: [rehypeCardImages],
    }),
  },
  // Astro prefixes `base` onto the source but not the destination, hence it spelled out here.
  redirects: {
    // Sidebar group labels are not routes, so send them to the group's first page.
    "/docs/cards": `${base}/docs/cards/stats/`,
    "/docs/customization": `${base}/docs/customization/common-options/`,
  },
  integrations: [
    react(),
    starlight({
      title: "GitHub Stats Extended",
      description: "Dynamically generate GitHub stats for your READMEs.",
      logo: { src: "./src/assets/appLogo64.png", alt: "" },
      // Starlight defaults to a favicon.svg this project does not ship.
      favicon: "/favicon.ico",
      head: [
        {
          tag: "link",
          attrs: { rel: "apple-touch-icon", href: `${base}/logo192.png` },
        },
        {
          tag: "link",
          attrs: { rel: "manifest", href: `${base}/manifest.json` },
        },
        { tag: "meta", attrs: { name: "theme-color", content: "#000000" } },
      ],
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/stats-organization/github-stats-extended",
        },
      ],
      plugins: [
        starlightLinksValidator({
          // The docs link to each other by site path, so a rename must fail the build.
          // `/api` and `/frontend` are not part of the docs, so they don't have matching pages.
          exclude: ["/api/**", "/frontend"],
        }),
      ],
      customCss: ["./src/styles/starlight-theme.css"],
      components: { SiteTitle: "./src/components/SiteTitle.astro" },
      sidebar: [
        { label: "Overview", slug: "docs" },
        {
          label: "Cards",
          items: [
            { label: "Stats Card", slug: "docs/cards/stats" },
            { label: "Top Languages Card", slug: "docs/cards/top-languages" },
            { label: "Repo Pin Card", slug: "docs/cards/repo-pin" },
            { label: "Gist Pin Card", slug: "docs/cards/gist-pin" },
            { label: "WakaTime Card", slug: "docs/cards/wakatime" },
          ],
        },
        {
          label: "Customization",
          items: [
            {
              label: "Common Options",
              slug: "docs/customization/common-options",
            },
            { label: "Theming", slug: "docs/customization/theming" },
            // Generated by packages/core scripts/generate-theme-readme.js.
            { label: "Available Themes", slug: "docs/customization/themes" },
            { label: "Locales", slug: "docs/customization/locales" },
            {
              label: "Aligning Cards",
              slug: "docs/customization/aligning-cards",
            },
          ],
        },
        { label: "Demo Gallery", slug: "docs/demos" },
        { label: "Run It Yourself", slug: "docs/deploy" },
        { label: "Fork Information", slug: "docs/fork" },
      ],
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
    /*
     * On Vercel the same deployment serves `/api` and `/frontend`, so the docs can reference cards by root-relative path.
     * Locally the two are separate servers, so forward `/api` to `pnpm dev:backend` to keep those paths working.
     */
    server: { proxy: { "/api": BACKEND_ORIGIN } },
    resolve: {
      conditions: ["@stats/source"],
      alias: [
        {
          find: "../fetchers/wakatime.js",
          replacement: path.resolve(
            import.meta.dirname,
            "src/wakatime-override.ts",
          ),
        },
      ],
    },
    // The backend code the wizard reuses imports `pg`, which never runs in the browser.
    build: {
      rolldownOptions: {
        external: ["pg"],
      },
    },
  },
});
