name: Update supported languages
on:
  workflow_dispatch:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │  ┌───────────── day of the month (1 - 31)
    #        │ │  │   ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │  │   │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │  │   │ │
    #        │ │  │   │ │
    #        │ │  │   │ │
    #        * *  *   * *
    - cron: "45 22 */7 * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-languages:
    if: github.repository == 'stats-organization/github-stats-extended'
    name: Generate Language Colors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run update-languages-json.js script
        run: pnpm --filter ./packages/core/ run generate-language-colors

      - name: Create Pull Request if upstream language file is changed
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "feat(core): update language colors"
          branch: "update_langs/patch"
          delete-branch: true
          title: Update languages colors
          body: >-
            The [generate-language-colors](https://github.com/stats-organization/github-stats-extended/actions/workflows/generate-language-colors.yml)
            workflow detected changes in the [upstream languages JSON
            file](https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml) and regenerated the local language colors JSON file.
          labels: "ci"
