name: Generate Theme Readme
on:
  push:
    branches:
      - master
    paths:
      - "packages/core/src/themes/index.js"
  workflow_dispatch:

permissions: {}

jobs:
  generate-theme-doc:
    runs-on: ubuntu-latest
    name: Generate theme doc

    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: write
      repository-projects: read
      security-events: read
      statuses: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Generate readme
        run: |
          pnpm --filter ./packages/core/ run theme-readme-gen

      - name: Create Pull Request if themes README has changed
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          commit-message: "feat(backend): update themes README"
          branch: "update_themes_readme/patch"
          delete-branch: true
          title: Update themes README
          body: "The
            [generate-theme-doc](https://github.com/stats-organization/github-stats-extended/actions/workflows/generate-theme-doc.yml)
            action found new/updated languages in the [upstream languages JSON
            file](https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml)."
          labels: "ci"
